<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProdiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'kode' => '88888',
                'konim' => null,
                'alias' => 'PJM',
                'nama' => 'Pondok - Jamiah',
                'aktif' => 'Y',
                'jenjang' => null,
                'nidn_kepala' => null,
                'nama_kepala' => null,
                'akreditasi' => '-',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 0,
                'user_id' => 8,
                'created_at' => '2021-01-09 06:53:15',
                'updated_at' => '2021-09-24 01:19:50',
                'token' => null,
            ],
            [
                'id' => 3,
                'kode' => '60202',
                'konim' => '29',
                'alias' => 'ESY',
                'nama' => 'Ekonomi Syariah',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2120048003',
                'nama_kepala' => "Robi'in, S.E., M.M.",
                'akreditasi' => 'B',
                'color' => '#7FFFD4',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:08:50',
                'updated_at' => '2025-09-29 15:18:34',
                'token' => '1dea9c69-1847-4384-ae3a-1fdff3e8d71b',
            ],
            [
                'id' => 4,
                'kode' => '70232',
                'konim' => '32',
                'alias' => 'BKI',
                'nama' => 'Bimbingan Dan Konseling Islam',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2102118703',
                'nama_kepala' => 'Muhammad Syafiq, S.Psi, M.Pd.',
                'akreditasi' => 'B',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:10:22',
                'updated_at' => '2025-09-29 15:19:09',
                'token' => null,
            ],
            [
                'id' => 5,
                'kode' => '70233',
                'konim' => '22',
                'alias' => 'KPI',
                'nama' => 'Komunikasi dan Penyiaran Islam',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2118069002',
                'nama_kepala' => 'Reiza Praselanova, M.I.Kom',
                'akreditasi' => 'B',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:11:36',
                'updated_at' => '2025-09-29 15:19:40',
                'token' => 'd6fd1322-5abe-4829-b63c-525fec253c77',
            ],
            [
                'id' => 6,
                'kode' => '74230',
                'konim' => '03',
                'alias' => 'AS-HK',
                'nama' => 'Hukum Keluarga Islam (Ahwal Al Syakhshiyah)',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2116067701',
                'nama_kepala' => 'Muhammad Zuhdi, M.H.I.',
                'akreditasi' => 'B',
                'color' => '#7FFFD4',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:12:35',
                'updated_at' => '2025-09-29 15:17:56',
                'token' => null,
            ],
            [
                'id' => 7,
                'kode' => '80230',
                'konim' => '14',
                'alias' => 'SKI',
                'nama' => 'Sejarah Peradaban Islam',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2129067301',
                'nama_kepala' => 'Samsul Huda, M.Pd.',
                'akreditasi' => 'B',
                'color' => '#7FFFD4',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:14:07',
                'updated_at' => '2025-09-29 15:20:14',
                'token' => null,
            ],
            [
                'id' => 8,
                'kode' => '86208',
                'konim' => '01',
                'alias' => 'PAI',
                'nama' => 'Pendidikan Agama Islam',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2126018401',
                'nama_kepala' => 'Dr. Ahmad Sulton, M.Pd.',
                'akreditasi' => 'B',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:15:24',
                'updated_at' => '2025-09-29 15:16:45',
                'token' => null,
            ],
            [
                'id' => 9,
                'kode' => '86231',
                'konim' => '20',
                'alias' => 'MPI',
                'nama' => 'Manajemen Pendidikan Islam',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2129047101',
                'nama_kepala' => 'Ahmad Misbah, M.Pd.',
                'akreditasi' => 'B',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:16:27',
                'updated_at' => '2025-09-29 15:17:20',
                'token' => null,
            ],
            [
                'id' => 10,
                'kode' => '88204',
                'konim' => '02',
                'alias' => 'PBA',
                'nama' => 'Pendidikan Bahasa Arab',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2126056801',
                'nama_kepala' => 'Dr. Munapi, M.Pd.',
                'akreditasi' => 'A',
                'color' => '#7FFFD4',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:17:49',
                'updated_at' => '2025-10-02 00:02:29',
                'token' => null,
            ],
            [
                'id' => 11,
                'kode' => '88104',
                'konim' => null,
                'alias' => 'PBAS2',
                'nama' => 'Pendidikan Bahasa Arab S2',
                'aktif' => 'Y',
                'jenjang' => 'S2',
                'nidn_kepala' => '80244',
                'nama_kepala' => 'Munapi, S.H.I, M.Pd.',
                'akreditasi' => 'C',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 72,
                'user_id' => 8,
                'created_at' => '2021-01-03 02:22:45',
                'updated_at' => '2021-09-23 13:22:08',
                'token' => null,
            ],
            [
                'id' => 12,
                'kode' => '86131',
                'konim' => null,
                'alias' => 'MPIS2',
                'nama' => 'Manajemen Pendidikan Islam S2',
                'aktif' => 'Y',
                'jenjang' => 'S2',
                'nidn_kepala' => '80230',
                'nama_kepala' => 'Dr. Sodikin, M.Pd',
                'akreditasi' => 'B',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 72,
                'user_id' => 8,
                'created_at' => '2021-01-03 02:25:15',
                'updated_at' => '2021-09-23 13:22:23',
                'token' => null,
            ],
            [
                'id' => 13,
                'kode' => '86008',
                'konim' => null,
                'alias' => 'PAIS3',
                'nama' => 'Pendidikan Agama Islam S3',
                'aktif' => 'Y',
                'jenjang' => 'S3',
                'nidn_kepala' => '80121',
                'nama_kepala' => 'Dr. Romli, M.Pd.',
                'akreditasi' => 'C',
                'color' => '#7FFFD4',
                'max_sks_skripsi' => 72,
                'user_id' => 8,
                'created_at' => '2021-01-03 02:30:36',
                'updated_at' => '2021-09-23 13:24:49',
                'token' => null,
            ],
            [
                'id' => 14,
                'kode' => '99999',
                'konim' => null,
                'alias' => 'PYY',
                'nama' => 'Pondok - Yayasan',
                'aktif' => 'Y',
                'jenjang' => null,
                'nidn_kepala' => null,
                'nama_kepala' => null,
                'akreditasi' => '-',
                'color' => '#F0F8FF',
                'max_sks_skripsi' => 0,
                'user_id' => 8,
                'created_at' => '2021-10-19 10:40:38',
                'updated_at' => '2021-10-19 10:40:41',
                'token' => null,
            ],
            [
                'id' => 15,
                'kode' => '88204',
                'konim' => null,
                'alias' => 'PBAX',
                'nama' => 'XXXXPBAXXPBAXXPBAXXPBAXXPBAXXX',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '80125',
                'nama_kepala' => 'Moh. Tohiri Habib, M.Pd.',
                'akreditasi' => 'A',
                'color' => '#7FFFD4',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2020-12-31 07:17:49',
                'updated_at' => '2020-12-31 07:17:49',
                'token' => null,
            ],
            [
                'id' => 16,
                'kode' => '70234',
                'konim' => null,
                'alias' => 'MHU',
                'nama' => 'Manajemen Haji dan Umroh',
                'aktif' => 'Y',
                'jenjang' => 'S1',
                'nidn_kepala' => '2108118903',
                'nama_kepala' => 'Mohammad Rofiuddin, M.M.',
                'akreditasi' => '-',
                'color' => '#DC143C',
                'max_sks_skripsi' => 145,
                'user_id' => 8,
                'created_at' => '2025-09-07 21:32:13',
                'updated_at' => '2025-09-29 15:21:09',
                'token' => null,
            ],
        ];

        foreach ($data as $item) {
            DB::table('prodi')->updateOrInsert(
                ['id' => $item['id']],
                $item
            );
        }
    }
}
